---
name: PHEV
version: 1.4.1
slug: phev
description: Mitsubishi Outlander PHEV
arch: [armhf, armv7, aarch64, amd64, i386]
url: https://github.com/buxtronix/phev2mqtt
startup: application
boot: auto
init: false
apparmor: true
options:
  mqtt_server:
  mqtt_user:
  mqtt_password:
  debug: false
schema:
  mqtt_server: str
  mqtt_user: str
  mqtt_password: str
  debug: bool
